# Generated by Django 4.2.8 on 2024-04-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_candidate_votes_delete_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_votes',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
