# Generated by Django 4.2.8 on 2024-04-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_alter_candidate_votes_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_over',
            field=models.BooleanField(default=False),
        ),
    ]
